version: '2'
services:
    mongodb:
        image: mongo:latest
        restart: always
        container_name: mongodb
        ports:
        - 27017:27017
        volumes:
        - ./mongodb/data:/data/db
    flask-service:
        build:
            context: ./flask
        restart: always
        container_name: flask
        links:
            - "mongodb"
        depends_on:
            - mongodb
        ports:
            - 5000:5000
        environment:
            - "MONGO_HOSTNAME=mongodb"